name = "moonlight-discord"
main = "src/index.ts"
compatibility_date = "2024-04-05"

[vars]
DISCORD_APPLICATION_ID = "469805086290477057"

# [secrets]
# DISCORD_PUBLIC_KEY = "<discord-public-key>"
# DISCORD_TOKEN = "<discord-token>"
